spring:
  mail:
    host: smtp.ethereal.email
    port: 587
    username: river.daniel6@ethereal.email
    password: Ueed4tYQeBebEk3e5F
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
fantasy-team-mail-queue: fantasy-team-mail-queue